### ISSUE TITLE
[nodejs] WebSocket closed unexpectedly.

### ISSUE THREAD

**Issue by imnotjoel** [BitMEX/api-connectors#150]
Hi guys, I have the following issue. Hope you can give me a hand!

```
WebSocket [INFO]: Connected.
Connection opened.
Client initialized, data is flowing.
{"op":"subscribe","args":"order:XBTUSD"}
WebSocket [ERROR]: WebSocket closed with code 1006
Connection closed.
WebSocket [INFO]: Retry in 1000 ms
WebSocket [INFO]: Reconnecting...
WebSocket [ERROR]: Unexpected response from server [400]: {"error":"Nonce is not increasing. This nonce: 1528139622410000, last nonce: 1528139622410000"}
WebSocket [INFO]: The WebSocket will terminate. Please manually reconnect.
WebSocket [ERROR]: WebSocket closed unexpectedly.
Connection closed.
/Users/nosoyjoel/Documents/api-connectors-master/official-ws/nodejs/lib/createSocket.js:70
    if (!listeners.length) throw new Error('WebSocket closed. Please check errors above.');
                           ^

Error: WebSocket closed. Please check errors above.
    at WebSocketClient.wsClient.onend (/Users/nosoyjoel/Documents/api-connectors-master/official-ws/nodejs/lib/createSocket.js:70:34)
    at WebSocket.instance.on (/Users/nosoyjoel/Documents/api-connectors-master/official-ws/nodejs/lib/ReconnectingSocket.js:45:12)
    at WebSocket.emit (events.js:182:13)
    at closeConnection (/Users/nosoyjoel/Documents/api-connectors-master/official-ws/nodejs/lib/ReconnectingSocket.js:71:23)
    at IncomingMessage.response.on (/Users/nosoyjoel/Documents/api-connectors-master/official-ws/nodejs/lib/ReconnectingSocket.js:84:9)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

I tough it has to do with my connection.. But then I tried to run it in a ECS instance and I had the same issue. 

Thanks in advance!

**Comment by ryanfox** [comment]
Code 1006 means the connection was closed improperly. [See this stackoverflow answer](https://stackoverflow.com/a/19305172/777980) for more info.

Does it happen consistently every time, or is it sporadic?

**Comment by imnotjoel** [comment]
Hi @ryanfox  It happens always after ~4 minutes

**Comment by dannyluong408** [comment]
i've also had this issue while running a python websocket to the test.bitmex and it closes after about 24 hours.
Is there any way to handle this ?

**Comment by ryanfox** [comment]
@dannyluong408 it's not unexpected that the socket would get disconnected after that amount of time. If you want to reconnect it, you could wrap your code in a retry block.

@imnotjoel is your network connection stable in general? One way you could get more information is to enable DEBUG - this will produce large amounts of output though.

**Comment by lewisbarber** [comment]
I have this problem every single time. I don't seem to be able to catch the exception either for some reason (using Node lib)

**Comment by dannyluong408** [comment]
@ryanfox I try to wrap it in a retry by checking if "ws.connected" is false
Sometimes it also ws.recv's a blank message (had to handle that special case).
Why is the websocket connection so unstable even with reconnection?
Is a "reconnection" just reinitializing create_connection and subscribing to it again?

**Comment by annugaurish** [comment]
I have solved this problem by making changes in createSocket.js
Added following code in the createSocket function

wsClient.onreconnect = function() {
         wsClient.url = makeEndpoint(options);
		
	debug('Reconnecting to BitMEX at ', wsClient.url);
};

and in ReconnectionSocket.js added the following line in reconnect prototype
   this.onreconnect();

this is to be added before this.open(this.url);

**Comment by sandybradley** [comment]
Dear Bitmex community,

Thank you annugaurish for your corrections. My Bitmex node client now does not crash but still reconnects every few seconds with a 1006 error. The same code was working fine 3 days ago. Can anyone explain why the client is continually disconnecting all of a sudden?

Faithfully,

Alexander

**Comment by Xavier59** [comment]
Thanks @annugaurish ! This solution fix the problem. Pull request needed :)

**Comment by annugaurish** [comment]
Welcome:)

**Comment by pabx06** [comment]
same issue here a bit painful to have my bot stop completely from that crash...

**Comment by martincpt** [comment]
I solved this problem by sending a raw ping every minute.
 The client library has a socket variable holding the websocket object. So just setup an interval and send the ping like this:
`client.socket.send('ping');`

You may recieve messages like:

> Unable to parse incoming data: pong

But its not a big deal i guess.

**Comment by ever4cys** [comment]
I'm in the middle of trying @annugaurish 's solution. Let me see if it's working well. But I wonder why there's no pull request about this?

**Comment by fngrl** [comment]
We're having the same issue and @annugaurish solution does not seem to change anything.

**Comment by QuentinFAIDIDE** [comment]
@martincpt As a last resort I found this: https://github.com/sindresorhus/filter-console

**Comment by QuentinFAIDIDE** [comment]
@martincpt I think you can also set client.on('pong', callback)

**Comment by honey96dev** [comment]
I tried to fix with @annugaurish`s method, but that solution does not seem to change anything.

**Comment by nvrossett** [comment]
> I solved this problem by sending a raw ping every minute.
> The client library has a socket variable holding the websocket object. So just setup an interval and send the ping like this:
> `client.socket.send('ping');`
> 
> You may recieve messages like:
> 
> > Unable to parse incoming data: pong
> 
> But its not a big deal i guess.

This work to me

I just made a small change in my local in the file:
https://github.com/BitMEX/api-connectors/blob/master/official-ws/nodejs/lib/createSocket.js#L38

Adding an if, to not return this message if the answer is pong!

Resolved issue and no longer issues annoying message

Thanks for sharing

![image](https://user-images.githubusercontent.com/2110820/67697862-010cdf00-f988-11e9-9ac5-64da75569069.png)

**Comment by CRLakeDev** [comment]
I have noticed re-connection errors and tried the above method but did not solve the issue.

**Comment by pjs5983** [comment]
I used to @nvrossett solution. I sovled this problem by sending ping/pong

1.index.js
BitMEXClient.prototype.sendSubscribeRequest = function(table, symbol) {
  console.log(JSON.stringify({op: 'subscribe', args: `${table}:${symbol}`}))
  this.socket.send(JSON.stringify({op: 'subscribe', args: `${table}:${symbol}`}));

  /* Bitmex Websocket First Send PIng */
  this.socket.send('ping');
};

2. /lib/createSocket.js
  wsClient.onmessage = function(data) {
    try {
      data = JSON.parse(data);
    } catch(e) {
      if (data != 'pong'){
        bmexClient.emit('error', 'Unable to parse incoming data:', data);
        return;
      } else {
        /* Bitmex Websocket ReSend PIng */
        debug('Bitmex Websocket Send PIng wait 5 second...');

        setTimeout(function() {
        wsClient.send('ping', );
        }, 5000);
      }
    }
