### ISSUE TITLE
ws-official - nodejs - Order updates show empty arrays for filled or cancelled

### ISSUE THREAD

**Issue by sandybradley** [BitMEX/api-connectors#166]
Dear Bitmex team,

Using the official ws nodejs client to subscribe to order updates, we are experiencing inconsistencies. For newly placed orders, we receive updates as expected. However, when an order is filled or cancelled, we receive empty arrays instead of data. This seems like a Bitmex bug or am I missing something?

Faithfully,

Alexander

**Comment by kevzettler** [comment]
@sandybradley can you provide example code on how the subscription is initiated?

specifically a `client.addStream` hook?

**Comment by sandybradley** [comment]
Thank you for your response Kev. Presently, we are using the position updates to figure out our order /execution positions, as the order and execution channels returned data sporadically, at best, whether subscribed to individually or with the wildcard (code below) ... 

If it helps,  the order update channel seems to work best around 4 pm every day!

var markets=[
    'XBTUSD',
    'XBTU18',
    'ETHU18',
    'LTCU18',
    'XRPU18',
    'BCHU18',
    'EOSU18',
    'ADAU18'
  ];
  for (let market of markets){
      client.addStream(market, 'order', function(data2, symbol1, tableName1) {
        console.log(data2);
      });
      client.addStream(market, 'execution', function(data3, symbol3, tableName3) {
         console.log(data3);
      });
  }

**Comment by annugaurish** [comment]
Hi

I am also facing the same kind of issue.

Sometimes getting blank data from testnet.bitmex while my order gets filled.
here is my code used to call bitmex by nodejs api

client.addStream(symbol, 'order', function(data, symbol, tableName) {
});

**Comment by jgabios** [comment]
Hi,

I guess I face the same issue.
Here is my code:
-----------------------------
'use strict';
const BitMEXClient = require('./index');
const util = require('util');

const client = new BitMEXClient({testnet: false, apiKeyID: APIKEYID, apiKeySecret: APIKEYSECRET});
// handle errors here. If no 'error' callback is attached. errors will crash the client.
client.on('error', function(e){
    console.error(e);
});
client.on('open', () => console.log('Connection opened.'));
client.on('close', () => console.log('Connection closed.'));
client.on('initialize', () => console.log('Client initialized, data is flowing.'));

/*
 * I register to this stream to get the latest price.
 */
client.addStream('XBTUSD', 'trade', function (data, symbol, tableName) {
    var last = data[data.length - 1],
        now = (new Date()).getTime();
    //console.log('Current state: ' +last.price);
    if(!last) {
        console.log("----- error trade data -------");
        console.log(util.inspect(data, false, null));
        console.log("----- error trade data -------");
    }
});

/*
 * This stream alerts me of any change to the orders. If it is filled, closed, etc...
 */
client.addStream('XBTUSD', 'order', function (data, symbol, tableName) {
    console.log("----- ORDER data -------");
    console.log(util.inspect(data, false, null));
    console.log("----- ORDER data -------");
});

/*
 * This stream alerts me of any change to my position. If it is filled, closed, entry price, liquidation price
 */
client.addStream('XBTUSD', 'position', function (data, symbol, tableName) {
    if(data && data.length > 0 && data[0].currentQty != 0) {
        console.log("----- POZ data -------");
        console.log(util.inspect(data, false, null));
        console.log("----- POZ data -------");
    }
});

/*
 * This stream alerts me of any executions of my orders. The results of the executions are seen in the position stream
 */
client.addStream('XBTUSD', 'execution', function (data, symbol, tableName) {
    console.log("----- EXE data -------");
    console.log(util.inspect(data, false, null));
    console.log("----- EXE data -------");
});
-------------------------------------------

Here is my result:
----- EXE data -------
[]
----- EXE data -------
----- EXE data -------
[]
----- EXE data -------
----- EXE data -------
[]
----- EXE data -------
----- EXE data -------
[]
----- EXE data -------
----- EXE data -------
[]
----- EXE data -------
----- EXE data -------
[]
----- EXE data -------
----- EXE data -------
[]
----- EXE data -------
----- EXE data -------
[]
----- EXE data -------
-------------------------------------------------------
However, I have this code running on 2 machines, on a stretch ubuntu and on a jessie ubuntu. It works fine on jessie [no empty arrays] but not on stretch.
both running nodejs 0.7.5 using nvm.

**Comment by annugaurish** [comment]
I have solved my issue by making changes in code for 'order'.

**onAction** function in the **deltaParser.js** file was returning new updates only for action partial.
But when order filled bitmex returns action as 'update'. so I had made changes in **deltaParser.js** file

Commented this code.
//if (action !== 'partial' && !isInitialized(tableName, symbol, client)) return [];

// Partials initialize the table, so there's a different signature.
if (action === 'partial' || action === 'insert' || action === 'update') return this._partial(tableName, symbol, client, data);

On action 'update', it will not return the whole data array. but not a blank array.

**Note:** I have made this changes as per my requirement, please check your requirement before changing.

**Comment by nice-table** [comment]
This sounds similar to an issue I had.

My case:

Account with no current active orders:

* Connect to WS API using bitmex-realtime-api@0.3.0 with https://github.com/BitMEX/api-connectors/pull/134 applied
* Post bulk order
* An 'insert' action is sent, but since the table isn't initialized yet, it's discarded
* As a result, the submitted orders do not appear in the UI

If I had active orders before submitting new orders, then the data would be updated correctly.

I was able to hack together a fix that solved that specific case:
```js
// deltaParser.js
   /**
    * Called when data comes in via the websocket.
    *
@@ -33,21 +32,45 @@ module.exports = {
    * @return {Array}            Updated data.
    */
   onAction(action, tableName, symbol, client, data) {
+    // temp fix for new orders when none existed previously
+    if (
+      tableName === "order" &&
+      action === "insert" &&
+      !isInitialized(tableName, symbol, client)
+    ) {
+      data.keys = ["orderID"];
+      return this._partial(tableName, symbol, client, data);
+    }
```

**Comment by nice-table** [comment]
@ryanfox Just to clarify, I think `partial` isn't sent at all upon subscription on empty tables. In my case this would be fixed if the API returned a `partial` with an empty array. If I remember correctly, no `partial` was sent when subscribing to an empty table, so the `isInitialized` function would always return `false` for that table until you reconnected after adding an order.

**Comment by sandybradley** [comment]
Awefull hangover.
Can you send me the code for buying to close?

Arbs are live, with wallet checks. Currently 4 exchanges, adding Binance
back now to make 5.
http://197.245.235.2:5000/?select[%3Edprice]%20from%20arbs

Do you have an EXX account?

**Comment by huyb1991** [comment]
@nice-table I got the same isssue, nice explain.
In case `{"op":"subscribe","args":"order:XBTUSD"}`, then add a new order, the API didn't return data.
If I refresh again, data.lenght is number of orders and it works.

**Comment by ldupisani** [comment]
Testing with 'order', '*'

In deltaParser.js

function isInitialized(tableName, symbol, client) {
  return client._data[tableName] && client._data[tableName][symbol];
}

This will return false when the symbol is not defined yet. And unless there were existing orders from the start the "symbol" in that table name will not be defined.... So somewhere that needs to be initialised when an order changes comes in fro a symbol that didn't have order before.

**Comment by ldupisani** [comment]
For now i'm just trying with this... will needs to see if it leads to any downstream data corruption.

function isInitialized(tableName, symbol, client) {
	if (!client._data[tableName]) {
		return false;
	} else if (!client._data[tableName][symbol]) {
		client._data[tableName][symbol] = [];
	}
	return true;
}

**Comment by STRML** [comment]
Fixed in a6a2236325edbe178e70ebc5164cd3eef977bfb0

**Comment by eolszewski** [comment]
@STRML

This is still happening - try it with the latest version.

clients.addStream('*', 'order', (data: any, symbol: string) => { console.log('data: ', data); });

Will give you data: [] when you place an order if it was instantiated without any orders on the books.

**Comment by STRML** [comment]
Thanks @eolszewski , you're correct. I'm working on an update now to fix this. There is a significant amount of ambiguity in the code around subscribing by symbol only, by table only, and by table and symbol. This needs to be cleaned up & tests written.
