### ISSUE TITLE
"This request has expired" error

### ISSUE THREAD

**Issue by mcast123** [BitMEX/api-connectors#202]
Hello,
I'm getting this error when placing an order:

{'error': {'message': 'This request has expired - `expires` is in the past. Current time: 1534543214', 'name': 'HTTPError'}}

Any ideas how to solve it?

**Comment by Madward** [comment]
The error indicates your "expires" field is set in the past, which would most likely be the result of a difference in time zones.

Check the difference in hours between your system time and BitMEX's "current time", and offset the "expires" field by the correct amount of hours/half-hours that separates your time zones.

**Comment by ryanfox** [comment]
If you are still experiencing this issue, the previous commenter is correct - if you get "expires is in the past" errors, set `expires` farther in the future.

**Comment by cheezman111** [comment]
I also had this error message appear. When I compared my system time to the 'Current time' returned by the Bitmex server I found that my clock was about 6 or 7 seconds slow relative to theirs. This was easily fixed by synchronizing my system clock.

**Comment by biahoi** [comment]
I have the same issue. I have syncronized the system clock. It got a little better. But it does not totaly solved. Sometimes it still happens. And the error shows up not only after orders that requires time stamp (such as Create_order(..)) bit also for orders such as fetchOrderBook().
The time on my PC shows exactly as it shows on the top right corner of Bitmex windows.
When I fetch the exchange.millisecond() and it give the same time as my PC time as by Date.now()

**Comment by pastet89** [comment]
The NTP synchronization must be running at least each few seconds, but indeed, it is not 100% reliable. One way to solve this problem is to handle this potential error with a decorator, which, if the error occurs, shifts the system clock ahead with 1-2 seconds and retries the request.

**Comment by dwihdyn** [comment]
Hi @Madward & @pastet89

Can you share with us how can we synchronise the system time with the "Bitmex" time and shifts the clock ashead with 1-2 seconds ?

facing the same error here and having trouble doing that for quite some time, thank you!

**Comment by sesangsokuro** [comment]
https://stackoverflow.com/questions/5222951/easy-way-to-get-the-correct-time-in-python
