### ISSUE TITLE
How can I get order info with Delta-Server

### ISSUE THREAD

**Issue by hunzhigaga** [BitMEX/api-connectors#247]
Hi，I want use Delta-Server to get position、opening orders.

I got position info from:
http://127.0.0.1:4444/position?symbol=XBTUSD

but,I can't get order info from:
http://127.0.0.1:4444/order
or
http://127.0.0.1:4444/order?symbol=XBTUSD

Is there any offical documents about delta-server? Or, I can get the correct params from anywhere else?

Thanks very much!

---------------------------------------------------------------------
I got the error message below:

TypeError: data.map is not a function
and
TypeError: Cannot read property &#39;XBTUSD&#39; of undefined

---------------------------------------------------------------------

**Comment by CoreyNelson** [comment]
If you want the orderbook you have to modify your config to subscribe to orderBookL2 and then make a REST call like this:
http://localhost:4444/orderBookL2?symbol=XBTUSD

**Comment by hunzhigaga** [comment]
> If you want the orderbook you have to modify your config to subscribe to orderBookL2 and then make a REST call like this:
> http://localhost:4444/orderBookL2?symbol=XBTUSD

Thank you. But, I mean the http://127.0.0.1:4444/order?symbol=XBTUSD is  not work :)

Finally, I find reason. I have to open a new order and then I can get orders from  that url no matter if there is a opening order. I‘m not sure if it is a BUG.  I decide to use websocket client by myself.

**Comment by ivankia** [comment]
> Hi，I want use Delta-Server to get position、opening orders.
> 
> I got position info from:
> http://127.0.0.1:4444/position?symbol=XBTUSD
> 
> but,I can't get order info from:
> http://127.0.0.1:4444/order
> or
> http://127.0.0.1:4444/order?symbol=XBTUSD
> 
> Is there any offical documents about delta-server? Or, I can get the correct params from anywhere else?
> 
> Thanks very much!
> 
> I got the error message below:
> 
> TypeError: data.map is not a function
> and
> TypeError: Cannot read property 'XBTUSD' of undefined

Hi. Did not found any updates with that error ("TypeError: data.map is not a function"). So I fixed it in that way:

File: official-ws/nodejs/index.js

Fixed function:

function clone(data) {
    return Object.keys(data).map(function(key) {
        return [Number(key), data[key]];
    });
}

FYI: JS Objects are not Iterable but we can convert 'em into Array :) - so that was the problem

**Comment by pastet89** [comment]
Getting the same issue. Can not access orders feed even if I have an open order. Tried the suggestions of @ivankia  and @hunzhigaga, the problem is still present.
