### ISSUE TITLE
[Bug] bitmex-realtime-api does not return order data when there is no orders initially

### ISSUE THREAD

**Issue by whjn011205** [BitMEX/api-connectors#294]
When you launch BIIMEXCLIENT when you do not have any initial orders,  and then you create a new order, the order does not return anything. 

At deltaParser.ts line93 function(isInitialized): this function will return false when  because client._data['order'] does not exist since in the beginning, there is no active orders

**Comment by Madward** [comment]
Lots of issues referencing the problem, if any of them can help you:

#259 
#210
#203
#166

**Comment by traceur91** [comment]
@Madward any updates on this issue?

**Comment by STRML** [comment]
Fixed in a6a2236325edbe178e70ebc5164cd3eef977bfb0

**Comment by eolszewski** [comment]
@STRML 

This is still happening - try it with the latest version.

`clients.addStream('*', 'order', (data: any, symbol: string) => {
      console.log('data: ', data);
    });`

Will give you `data:  []` when you place an order if it was instantiated without any orders on the books.
