### ISSUE TITLE
Missing module websocket-stream from delta-server

### ISSUE THREAD

**Issue by bjschnei** [BitMEX/api-connectors#3]
module.js:472
    throw err;
    ^

Error: Cannot find module 'websocket-stream'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/bjschnei/bmx/third_party/api-connectors/official-ws/nodejs/lib/createSocket.js:1:82)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by STRML** [comment]
Thanks - that module's not actually used, fixed in the latest commit.

**Comment by bjschnei** [comment]
Was this fix submitted?  I am still seeing the above error after a pull.

**Comment by STRML** [comment]
@bjschnei My apologies; pushed now.
